language: c

python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - zlib1g-dev

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  # install Lua
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make rockspecs/lluv-websocket-scm-0.rockspec --deps-mode=none
  - luarocks make rockspecs/lua-websockets-lluv-scm-0.rockspec --deps-mode=none

before_script:
  - pip install --user autobahntestsuite
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
  - luarocks show lua-cjson || luarocks install lua-cjson
  - luarocks show lunitx || luarocks install lunitx

script: 
  - cd test

  # test with lzlib
  - luarocks install lzlib && lunit.sh test_deflate.lua

  # test with lua-zlib
  - if [ "$LUA" != "lua 5.3" ]; then
    luarocks remove lzlib && luarocks install lua-zlib && lunit.sh test_deflate.lua;
    fi

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
